### ISSUE TITLE
Dependency on monoid-extras>0.5?

### ISSUE THREAD

**Issue by uebayasi** [diagrams/geometry#6]
Disclaimer: I'm clueless about Haskell ecosystem

I can't build geometry because of missing monoid-extras>0.5.  I checked [1] but it says 0.5.

[1] https://github.com/diagrams/monoid-extras

**Comment by cchalmers** [comment]
Right, sorry. That's because I'm depending on the `strict-coproduct` branch. I'll try to get that merged into master soon.

**Comment by byorgey** [comment]
I removed the lower bound for now.  Once the `strict-coproduct` branch gets merged we can put it back if we want.
